# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:54:27+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class BidPercentages(BaseModel):
    basis: Optional[str] = Field(
        None,
        description="The basis by which the ad rate is calculated. Valid Values: ITEM and TRENDING For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/recommendation/types/api:Basis'>eBay API documentation</a>",
    )
    value: Optional[str] = Field(
        None,
        description='The bid percentage data is a single precision value, as calculated by the associated basis. In Promoted listings ad campaigns, the bid percentage (also known as the ad rate) is a user-defined value that sets the level that eBay raises the visibility of the listing in the marketplace. It is also the rate that is used to calculate the Promoted Listings fee. Minimum value: 1.0 &nbsp; Maximum value: 100.0',
    )


class ErrorParameter(BaseModel):
    name: Optional[str] = Field(None, description='The object of the error.')
    value: Optional[str] = Field(None, description='The value of the object.')


class FindListingRecommendationRequest(BaseModel):
    listingIds: Optional[List[str]] = Field(
        None,
        description='A comma-separated list of listing IDs for which you want Promoted Listings ad configuration information. Currently, this method accepts only listingId values from the Trading API. Max: 500 listing IDs',
    )


class Ad(BaseModel):
    bidPercentages: Optional[List[BidPercentages]] = Field(
        None,
        description='This field returns information that you can use to configure the bidPercentage field in a Promoted Listings campaign. Note: Currently, ITEM and TRENDING are the only supported bid percentage types. The ITEM suggested bid percentages are tailored to each of your items and are designed to help you stay competitive while finding an optimal balance between performance and cost. The recommendations are calculated based on a variety of factors that may include item attributes, seasonality, past performance, and current competition for each of your listings. The TRENDING suggested bid percentages are calculated by reviewing the category level average ad rates in the marketplace. Setting the bidPercentage of your ad campaign based on these rate recommendations will help the items in the campaign be competitive with other items in the marketplace by improving their chances of being displayed more often in the marketplace.',
    )
    promoteWithAd: Optional[str] = Field(
        None,
        description="An enum whose values describe whether or not eBay recommends you place the associated listing in a Promoted Listings ad campaign. IDs deemed RECOMMENDED by eBay are the listings with the highest potential of benefiting from being promoted. The recommendation calculation is based on marketplace trends, like buyer demand and the competition in the item&rsquo;s category. Note: A promoteWithAd value cannot be calculated for listings that are part of Promoted Listings campaigns. Because of this, if you call findListingRecommendations with a specific set of listing IDs, the promoteWithAd field is not returned for any of the listings that are involved in a promotion. However, as long as they are eligible, the trending bidPercentage is returned for all specified listings, even if they are part of an ad campaign. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/recommendation/types/api:PromoteWithAd'>eBay API documentation</a>",
    )


class Error(BaseModel):
    category: Optional[str] = Field(None, description='Identifies the type of erro.')
    domain: Optional[str] = Field(
        None,
        description='Name for the primary system where the error occurred. This is relevant for application errors.',
    )
    errorId: Optional[int] = Field(
        None, description='A unique number to identify the error.'
    )
    inputRefIds: Optional[List[str]] = Field(
        None,
        description='An array of request elements most closely associated to the error.',
    )
    longMessage: Optional[str] = Field(
        None, description='A more detailed explanation of the error.'
    )
    message: Optional[str] = Field(
        None,
        description="Information on how to correct the problem, in the end user's terms and language where applicable.",
    )
    outputRefIds: Optional[List[str]] = Field(
        None,
        description='An array of request elements most closely associated to the error.',
    )
    parameters: Optional[List[ErrorParameter]] = Field(
        None,
        description='An array of name/value pairs that describe details the error condition. These are useful when multiple errors are returned.',
    )
    subdomain: Optional[str] = Field(
        None,
        description='Further helps indicate which subsystem the error is coming from. System subcategories include: Initialization, Serialization, Security, Monitoring, Rate Limiting, etc.',
    )


class MarketingRecommendation(BaseModel):
    ad: Optional[Ad] = Field(
        None,
        description='An object that contains Promoted Listings recommendations and information related to the associated listing ID.',
    )
    message: Optional[str] = Field(
        None,
        description='A message that can conditionally accompany the listing information.',
    )


class ListingRecommendation(BaseModel):
    listingId: Optional[str] = Field(
        None,
        description='An ID that identifies the active listing associated with the eBay recommendations.',
    )
    marketing: Optional[MarketingRecommendation] = Field(
        None,
        description='This return object provides the eBay recommendations and information related to the associated listing ID. The container currently returns the AD recommendation type, which contains information that sellers can use to configure Promoted Listings ad campaigns. This container is returned with each ListingRecommendation object, except when: The listing ID is not eligible for Promoted Listings The listing ID is currently in a Promoted Listings campaign The listing ID is invalid',
    )


class PagedListingRecommendationCollection(BaseModel):
    href: Optional[str] = Field(
        None, description='The URI of the current page of results from the result set.'
    )
    limit: Optional[int] = Field(
        None,
        description='The number of items returned on a single page from the result set. This value can be set in the request with the limit query parameter.',
    )
    listingRecommendations: Optional[List[ListingRecommendation]] = Field(
        None,
        description='Returns a list of listingRecommendations, where each element in the list offers recommendations for the associated listingId. Which elements are returned depend on how you structure the request. For example, if you request recommendations for all of a sellers listings (by leaving the request payload empty), ad recommendations are returned only for those listings where promoteWithAd is set to RECOMMENDED.',
    )
    next: Optional[str] = Field(
        None,
        description='The URI for the following page of results. This value is returned only if there is an additional page of results to display from the result set. Max length: 2048',
    )
    offset: Optional[int] = Field(
        None,
        description='The number of results skipped in the result set before listing the first returned result. This value can be set in the request with the offset query parameter. Note: The items in a paginated result set use a zero-based list where the first item in the list has an offset of 0.',
    )
    prev: Optional[str] = Field(
        None,
        description='The URI for the preceding page of results. This value is returned only if there is a previous page of results to display from the result set. Max length: 2048',
    )
    total: Optional[int] = Field(
        None,
        description='The total number of items retrieved in the result set. If no items are found, this field is returned with a value of 0.',
    )
